# https://github.com/apps/settings

repository:
  default_branch: main
  name: invest-tester
  description: InvestTester | Simulate investment portfolios and algorithmic trading strategies
  topics: backtest, algo-trading, finance, stock-market
  homepage: https://InvestTester.com
  private: true
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: true
  delete_branch_on_merge: true
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

branches:
  - name: main
    protection:
      enforce_admins: false
      allow_force_pushes: true
      required_linear_history: true
      restrictions: null
      allow_deletions: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: [ 'test' ]
